name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
    - name: Install dependencies
      run: dotnet restore
    - name: Build Linux-x64 Standalone
      run: dotnet build --configuration Release /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary --runtime linux-x64 --output bin/release/netcoreapp3.1/publish --self-contained
    - name: Build OSX-x64 Standalone
      run: dotnet build --configuration Release /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary --runtime osx-x64 --output bin/release/netcoreapp3.1/publish --self-contained
    - name: Build Windows-x64 Standalone
      run: dotnet build --configuration Release /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary --runtime win-x64 --output bin/release/netcoreapp3.1/publish --self-contained
    - name: Test
      run: dotnet test --no-restore --verbosity normal
